
services:
  db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: diplomas
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db-mysql.sql:/docker-entrypoint-initdb.d/db-mysql.sql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  api:
    build: ./api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/diploma
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=userpassword
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - db
      - rabbitmq
      - redis

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

  worker:
    build: ./worker
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
      - QUEUE_NAME=diplomasQueue
      - MINIO_ENDPOINT=minio
      - MINIO_ACCESS_KEY=minio_access_key
      - MINIO_SECRET_KEY=minio_secret_key
      - MINIO_BUCKET=diplomas
      - CHROME_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
    depends_on:
      - rabbitmq
      - minio
      - db
    volumes:
      - ./worker:/worker

volumes:
  rabbitmq_data:
  minio_data: